FROM node:16.13.2-slim

# Install tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY . .

RUN yarn

RUN yarn build

RUN npx prisma generate

EXPOSE 3002