version: '3.4'
services:
  postgres:
    image: postgres:13.7
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: crypto_be_db
      POSTGRES_LOG: 1
    ports:
      - 5432:5432
  api:
    build:
      context: ..
      dockerfile: ./Dockerfile.dev
    ports:
      - 3002:3002
    depends_on:
      - postgres
    volumes:
      - ../src:/app/src
      - ../nodemon.json:/app/nodemon.json
    command: yarn dev
    env_file:
      - ../.env
