version: '3.4'
services:
  db:
    image: postgres:13.7
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  api:
    build:
      context: ..
      dockerfile: ./Dockerfile.dev
    ports:
      - "3002:3002"
    depends_on:
      - db
    volumes:
      - ../src:/app/src
      - ../nodemon.json:/app/nodemon.json
    command: yarn dev
    env_file:
      - ../.env
